// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  shareId: __t.string().primaryKey().name("share_id"),
  expenseId: __t.string().name("expense_id"),
  phone: __t.string(),
  role: __t.string(),
  status: __t.string(),
  fixedCents: __t.option(__t.i64()).name("fixed_cents"),
  amountCents: __t.i64().name("amount_cents"),
  responded: __t.bool(),
  followupCount: __t.u32().name("followup_count"),
  lastFollowupAt: __t.option(__t.timestamp()).name("last_followup_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
