// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  actionId: __t.string(),
  kind: __t.string(),
  groupId: __t.option(__t.string()),
  toPhone: __t.option(__t.string()),
  targetMessageId: __t.option(__t.string()),
  text: __t.option(__t.string()),
  reaction: __t.option(__t.string()),
  expenseId: __t.option(__t.string()),
  purpose: __t.string(),
  sendAfter: __t.timestamp(),
};
