// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  itemId: __t.string().primaryKey().name("item_id"),
  expenseId: __t.string().name("expense_id"),
  position: __t.u32(),
  description: __t.string(),
  quantity: __t.u32(),
  amountCents: __t.i64().name("amount_cents"),
});
