// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Claims = __t.object("Claims", {
  claimId: __t.string(),
  itemId: __t.string(),
  expenseId: __t.string(),
  phone: __t.string(),
  sourceMessageId: __t.string(),
  createdAt: __t.timestamp(),
});
export type Claims = __Infer<typeof Claims>;

export const Expenses = __t.object("Expenses", {
  expenseId: __t.string(),
  groupId: __t.string(),
  payerPhone: __t.option(__t.string()),
  description: __t.string(),
  sourceMessageId: __t.string(),
  splitMode: __t.string(),
  status: __t.string(),
  subtotalCents: __t.option(__t.i64()),
  taxCents: __t.i64(),
  tipCents: __t.i64(),
  feesCents: __t.i64(),
  discountCents: __t.i64(),
  totalCents: __t.i64(),
  objectionDeadline: __t.option(__t.timestamp()),
  claimDeadline: __t.option(__t.timestamp()),
  proposalMessageId: __t.option(__t.string()),
  settleMessageId: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  finalizedAt: __t.option(__t.timestamp()),
});
export type Expenses = __Infer<typeof Expenses>;

export const Groups = __t.object("Groups", {
  groupId: __t.string(),
  ledgerId: __t.string(),
  displayName: __t.option(__t.string()),
  timezone: __t.string(),
  onboardingStatus: __t.string(),
  createdAt: __t.timestamp(),
});
export type Groups = __Infer<typeof Groups>;

export const LedgerBalance = __t.object("LedgerBalance", {
  edgeId: __t.string(),
  fromLedgerMemberId: __t.string(),
  toLedgerMemberId: __t.string(),
  amountCents: __t.i64(),
});
export type LedgerBalance = __Infer<typeof LedgerBalance>;

export const LedgerBalances = __t.object("LedgerBalances", {});
export type LedgerBalances = __Infer<typeof LedgerBalances>;

export const LedgerClaim = __t.object("LedgerClaim", {
  ledgerClaimId: __t.string(),
  itemId: __t.string(),
  expenseId: __t.string(),
  ledgerMemberId: __t.string(),
});
export type LedgerClaim = __Infer<typeof LedgerClaim>;

export const LedgerClaims = __t.object("LedgerClaims", {});
export type LedgerClaims = __Infer<typeof LedgerClaims>;

export const LedgerExpense = __t.object("LedgerExpense", {
  expenseId: __t.string(),
  ledgerGroupId: __t.string(),
  payerLedgerMemberId: __t.option(__t.string()),
  description: __t.string(),
  splitMode: __t.string(),
  status: __t.string(),
  totalCents: __t.i64(),
  createdAt: __t.timestamp(),
});
export type LedgerExpense = __Infer<typeof LedgerExpense>;

export const LedgerExpenses = __t.object("LedgerExpenses", {});
export type LedgerExpenses = __Infer<typeof LedgerExpenses>;

export const LedgerGrants = __t.object("LedgerGrants", {
  grantId: __t.string(),
  identity: __t.identity(),
  groupId: __t.string(),
  createdAt: __t.timestamp(),
});
export type LedgerGrants = __Infer<typeof LedgerGrants>;

export const LedgerGroup = __t.object("LedgerGroup", {
  ledgerGroupId: __t.string(),
  displayName: __t.option(__t.string()),
  timezone: __t.string(),
  status: __t.string(),
});
export type LedgerGroup = __Infer<typeof LedgerGroup>;

export const LedgerGroups = __t.object("LedgerGroups", {});
export type LedgerGroups = __Infer<typeof LedgerGroups>;

export const LedgerItem = __t.object("LedgerItem", {
  itemId: __t.string(),
  expenseId: __t.string(),
  position: __t.u32(),
  description: __t.string(),
  quantity: __t.u32(),
  amountCents: __t.i64(),
});
export type LedgerItem = __Infer<typeof LedgerItem>;

export const LedgerItems = __t.object("LedgerItems", {});
export type LedgerItems = __Infer<typeof LedgerItems>;

export const LedgerMember = __t.object("LedgerMember", {
  ledgerMemberId: __t.string(),
  ledgerGroupId: __t.string(),
  name: __t.option(__t.string()),
});
export type LedgerMember = __Infer<typeof LedgerMember>;

export const LedgerMembers = __t.object("LedgerMembers", {});
export type LedgerMembers = __Infer<typeof LedgerMembers>;

export const LedgerSecrets = __t.object("LedgerSecrets", {
  secret: __t.string(),
  groupId: __t.string(),
  createdAt: __t.timestamp(),
});
export type LedgerSecrets = __Infer<typeof LedgerSecrets>;

export const LedgerShare = __t.object("LedgerShare", {
  ledgerShareId: __t.string(),
  expenseId: __t.string(),
  ledgerMemberId: __t.string(),
  role: __t.string(),
  status: __t.string(),
  amountCents: __t.i64(),
});
export type LedgerShare = __Infer<typeof LedgerShare>;

export const LedgerShares = __t.object("LedgerShares", {});
export type LedgerShares = __Infer<typeof LedgerShares>;

export const LedgerTransfer = __t.object("LedgerTransfer", {
  transferId: __t.string(),
  expenseId: __t.string(),
  fromLedgerMemberId: __t.string(),
  toLedgerMemberId: __t.string(),
  amountCents: __t.i64(),
  provider: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
  completedAt: __t.option(__t.timestamp()),
});
export type LedgerTransfer = __Infer<typeof LedgerTransfer>;

export const LedgerTransfers = __t.object("LedgerTransfers", {});
export type LedgerTransfers = __Infer<typeof LedgerTransfers>;

export const LineItemInput = __t.object("LineItemInput", {
  itemId: __t.string(),
  position: __t.u32(),
  description: __t.string(),
  quantity: __t.u32(),
  amountCents: __t.i64(),
});
export type LineItemInput = __Infer<typeof LineItemInput>;

export const LineItems = __t.object("LineItems", {
  itemId: __t.string(),
  expenseId: __t.string(),
  position: __t.u32(),
  description: __t.string(),
  quantity: __t.u32(),
  amountCents: __t.i64(),
});
export type LineItems = __Infer<typeof LineItems>;

export const Members = __t.object("Members", {
  memberId: __t.string(),
  ledgerMemberId: __t.string(),
  groupId: __t.string(),
  phone: __t.string(),
  name: __t.option(__t.string()),
  nessieCustomerId: __t.option(__t.string()),
  nessieAccountId: __t.option(__t.string()),
  joinedAt: __t.timestamp(),
  leftAt: __t.option(__t.timestamp()),
});
export type Members = __Infer<typeof Members>;

export const Messages = __t.object("Messages", {
  messageId: __t.string(),
  groupId: __t.option(__t.string()),
  senderPhone: __t.string(),
  isDm: __t.bool(),
  kind: __t.string(),
  text: __t.option(__t.string()),
  imageUrl: __t.option(__t.string()),
  replyToId: __t.option(__t.string()),
  reaction: __t.option(__t.string()),
  receivedAt: __t.timestamp(),
  intent: __t.option(__t.string()),
  confidence: __t.option(__t.f64()),
  status: __t.string(),
  error: __t.option(__t.string()),
});
export type Messages = __Infer<typeof Messages>;

export const ModuleConfig = __t.object("ModuleConfig", {
  configKey: __t.string(),
  ownerIdentity: __t.option(__t.identity()),
  demoMode: __t.bool(),
});
export type ModuleConfig = __Infer<typeof ModuleConfig>;

export const NessieSeedProgress = __t.object("NessieSeedProgress", {
  memberId: __t.string(),
  groupId: __t.string(),
  customerId: __t.option(__t.string()),
  accountId: __t.option(__t.string()),
  depositCreated: __t.bool(),
  seededBalanceCents: __t.i64(),
  updatedAt: __t.timestamp(),
});
export type NessieSeedProgress = __Infer<typeof NessieSeedProgress>;

export const Outbox = __t.object("Outbox", {
  actionId: __t.string(),
  kind: __t.string(),
  groupId: __t.option(__t.string()),
  toPhone: __t.option(__t.string()),
  targetMessageId: __t.option(__t.string()),
  text: __t.option(__t.string()),
  reaction: __t.option(__t.string()),
  expenseId: __t.option(__t.string()),
  expenseKey: __t.string(),
  purpose: __t.string(),
  sendAfter: __t.timestamp(),
  sendAfterMicros: __t.i64(),
  status: __t.string(),
  sentPhotonId: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  sentAt: __t.option(__t.timestamp()),
  error: __t.option(__t.string()),
});
export type Outbox = __Infer<typeof Outbox>;

export const SeederMember = __t.object("SeederMember", {
  memberId: __t.string(),
  groupId: __t.string(),
  phone: __t.string(),
  name: __t.option(__t.string()),
  customerId: __t.option(__t.string()),
  accountId: __t.option(__t.string()),
  depositCreated: __t.bool(),
  seededBalanceCents: __t.i64(),
});
export type SeederMember = __Infer<typeof SeederMember>;

export const SeederMembers = __t.object("SeederMembers", {});
export type SeederMembers = __Infer<typeof SeederMembers>;

export const ServiceRoles = __t.object("ServiceRoles", {
  identity: __t.identity(),
  role: __t.string(),
  createdAt: __t.timestamp(),
});
export type ServiceRoles = __Infer<typeof ServiceRoles>;

export const Shares = __t.object("Shares", {
  shareId: __t.string(),
  expenseId: __t.string(),
  phone: __t.string(),
  role: __t.string(),
  status: __t.string(),
  fixedCents: __t.option(__t.i64()),
  amountCents: __t.i64(),
  responded: __t.bool(),
  followupCount: __t.u32(),
  lastFollowupAt: __t.option(__t.timestamp()),
  updatedAt: __t.timestamp(),
});
export type Shares = __Infer<typeof Shares>;

export const TransferCompletionSchedule = __t.object("TransferCompletionSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  transferId: __t.string(),
});
export type TransferCompletionSchedule = __Infer<typeof TransferCompletionSchedule>;

export const Transfers = __t.object("Transfers", {
  transferId: __t.string(),
  groupId: __t.string(),
  expenseId: __t.string(),
  fromPhone: __t.string(),
  toPhone: __t.string(),
  amountCents: __t.i64(),
  provider: __t.string(),
  status: __t.string(),
  approvedByMessageId: __t.string(),
  createdAt: __t.timestamp(),
  completedAt: __t.option(__t.timestamp()),
  error: __t.option(__t.string()),
});
export type Transfers = __Infer<typeof Transfers>;

