// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  transferId: __t.string(),
  status: __t.string(),
  withdrawnDollars: __t.i64(),
  depositedDollars: __t.i64(),
  withdrawalId: __t.option(__t.string()),
  depositId: __t.option(__t.string()),
  attempts: __t.u32(),
  error: __t.option(__t.string()),
};
