// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddClaimReducer from "../add_claim_reducer";
import CancelOutboxReducer from "../cancel_outbox_reducer";
import ClaimModuleOwnerReducer from "../claim_module_owner_reducer";
import CreateTransferReducer from "../create_transfer_reducer";
import EnqueueOutboxReducer from "../enqueue_outbox_reducer";
import GrantServiceRoleReducer from "../grant_service_role_reducer";
import IngestMessageReducer from "../ingest_message_reducer";
import MarkOutboxReducer from "../mark_outbox_reducer";
import RecomputeExpenseReducer from "../recompute_expense_reducer";
import RedeemLedgerAccessReducer from "../redeem_ledger_access_reducer";
import RemoveClaimReducer from "../remove_claim_reducer";
import ResolveDisputeReducer from "../resolve_dispute_reducer";
import SeedCompletedTransferReducer from "../seed_completed_transfer_reducer";
import SetDemoModeReducer from "../set_demo_mode_reducer";
import SetGroupStatusReducer from "../set_group_status_reducer";
import SetLedgerSecretReducer from "../set_ledger_secret_reducer";
import SetLineItemsReducer from "../set_line_items_reducer";
import SetMemberNameReducer from "../set_member_name_reducer";
import SetMessageResultReducer from "../set_message_result_reducer";
import SetNessieIdsReducer from "../set_nessie_ids_reducer";
import SetSettleModeReducer from "../set_settle_mode_reducer";
import SetShareReducer from "../set_share_reducer";
import UpsertExpenseReducer from "../upsert_expense_reducer";

export type AddClaimParams = __Infer<typeof AddClaimReducer>;
export type CancelOutboxParams = __Infer<typeof CancelOutboxReducer>;
export type ClaimModuleOwnerParams = __Infer<typeof ClaimModuleOwnerReducer>;
export type CreateTransferParams = __Infer<typeof CreateTransferReducer>;
export type EnqueueOutboxParams = __Infer<typeof EnqueueOutboxReducer>;
export type GrantServiceRoleParams = __Infer<typeof GrantServiceRoleReducer>;
export type IngestMessageParams = __Infer<typeof IngestMessageReducer>;
export type MarkOutboxParams = __Infer<typeof MarkOutboxReducer>;
export type RecomputeExpenseParams = __Infer<typeof RecomputeExpenseReducer>;
export type RedeemLedgerAccessParams = __Infer<typeof RedeemLedgerAccessReducer>;
export type RemoveClaimParams = __Infer<typeof RemoveClaimReducer>;
export type ResolveDisputeParams = __Infer<typeof ResolveDisputeReducer>;
export type SeedCompletedTransferParams = __Infer<typeof SeedCompletedTransferReducer>;
export type SetDemoModeParams = __Infer<typeof SetDemoModeReducer>;
export type SetGroupStatusParams = __Infer<typeof SetGroupStatusReducer>;
export type SetLedgerSecretParams = __Infer<typeof SetLedgerSecretReducer>;
export type SetLineItemsParams = __Infer<typeof SetLineItemsReducer>;
export type SetMemberNameParams = __Infer<typeof SetMemberNameReducer>;
export type SetMessageResultParams = __Infer<typeof SetMessageResultReducer>;
export type SetNessieIdsParams = __Infer<typeof SetNessieIdsReducer>;
export type SetSettleModeParams = __Infer<typeof SetSettleModeReducer>;
export type SetShareParams = __Infer<typeof SetShareReducer>;
export type UpsertExpenseParams = __Infer<typeof UpsertExpenseReducer>;

