// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  ledgerShareId: __t.string().primaryKey().name("ledger_share_id"),
  expenseId: __t.string().name("expense_id"),
  ledgerMemberId: __t.string().name("ledger_member_id"),
  role: __t.string(),
  status: __t.string(),
  amountCents: __t.i64().name("amount_cents"),
});
