// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  expenseId: __t.string().primaryKey().name("expense_id"),
  ledgerGroupId: __t.string().name("ledger_group_id"),
  payerLedgerMemberId: __t.option(__t.string()).name("payer_ledger_member_id"),
  description: __t.string(),
  splitMode: __t.string().name("split_mode"),
  status: __t.string(),
  totalCents: __t.i64().name("total_cents"),
  createdAt: __t.timestamp().name("created_at"),
});
