// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  transferId: __t.string().primaryKey().name("transfer_id"),
  amountCents: __t.i64().name("amount_cents"),
  fromAccountId: __t.string().name("from_account_id"),
  toAccountId: __t.string().name("to_account_id"),
  completedAt: __t.option(__t.timestamp()).name("completed_at"),
});
