// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  memberId: __t.string().primaryKey().name("member_id"),
  groupId: __t.string().name("group_id"),
  phone: __t.string(),
  name: __t.option(__t.string()),
  customerId: __t.option(__t.string()).name("customer_id"),
  accountId: __t.option(__t.string()).name("account_id"),
  depositCreated: __t.bool().name("deposit_created"),
  seededBalanceCents: __t.i64().name("seeded_balance_cents"),
});
