// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  expenseId: __t.string(),
  phone: __t.string(),
  role: __t.string(),
  status: __t.string(),
  fixedCents: __t.option(__t.i64()),
  responded: __t.bool(),
  followupCount: __t.u32(),
  lastFollowupAt: __t.option(__t.timestamp()),
};
