// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  expenseId: __t.string(),
  groupId: __t.string(),
  payerPhone: __t.option(__t.string()),
  description: __t.string(),
  sourceMessageId: __t.string(),
  splitMode: __t.string(),
  status: __t.string(),
  subtotalCents: __t.option(__t.i64()),
  taxCents: __t.i64(),
  tipCents: __t.i64(),
  feesCents: __t.i64(),
  discountCents: __t.i64(),
  totalCents: __t.i64(),
  objectionDeadline: __t.option(__t.timestamp()),
  claimDeadline: __t.option(__t.timestamp()),
  proposalMessageId: __t.option(__t.string()),
  settleMessageId: __t.option(__t.string()),
  finalizedAt: __t.option(__t.timestamp()),
};
