// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  transferId: __t.string().primaryKey().name("transfer_id"),
  groupId: __t.string().name("group_id"),
  expenseId: __t.string().name("expense_id"),
  fromPhone: __t.string().name("from_phone"),
  toPhone: __t.string().name("to_phone"),
  amountCents: __t.i64().name("amount_cents"),
  provider: __t.string(),
  status: __t.string(),
  approvedByMessageId: __t.string().name("approved_by_message_id"),
  createdAt: __t.timestamp().name("created_at"),
  completedAt: __t.option(__t.timestamp()).name("completed_at"),
  error: __t.option(__t.string()),
});
