// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  expenseId: __t.string().primaryKey().name("expense_id"),
  groupId: __t.string().name("group_id"),
  payerPhone: __t.option(__t.string()).name("payer_phone"),
  description: __t.string(),
  sourceMessageId: __t.string().name("source_message_id"),
  splitMode: __t.string().name("split_mode"),
  status: __t.string(),
  subtotalCents: __t.option(__t.i64()).name("subtotal_cents"),
  taxCents: __t.i64().name("tax_cents"),
  tipCents: __t.i64().name("tip_cents"),
  feesCents: __t.i64().name("fees_cents"),
  discountCents: __t.i64().name("discount_cents"),
  totalCents: __t.i64().name("total_cents"),
  objectionDeadline: __t.option(__t.timestamp()).name("objection_deadline"),
  claimDeadline: __t.option(__t.timestamp()).name("claim_deadline"),
  proposalMessageId: __t.option(__t.string()).name("proposal_message_id"),
  settleMessageId: __t.option(__t.string()).name("settle_message_id"),
  createdAt: __t.timestamp().name("created_at"),
  finalizedAt: __t.option(__t.timestamp()).name("finalized_at"),
});
