// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  messageId: __t.string().primaryKey().name("message_id"),
  groupId: __t.option(__t.string()).name("group_id"),
  senderPhone: __t.string().name("sender_phone"),
  isDm: __t.bool().name("is_dm"),
  kind: __t.string(),
  text: __t.option(__t.string()),
  imageUrl: __t.option(__t.string()).name("image_url"),
  replyToId: __t.option(__t.string()).name("reply_to_id"),
  reaction: __t.option(__t.string()),
  receivedAt: __t.timestamp().name("received_at"),
  intent: __t.option(__t.string()),
  confidence: __t.option(__t.f64()),
  status: __t.string(),
  error: __t.option(__t.string()),
});
