// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  groupId: __t.string().primaryKey().name("group_id"),
  ledgerId: __t.string().name("ledger_id"),
  displayName: __t.option(__t.string()).name("display_name"),
  timezone: __t.string(),
  onboardingStatus: __t.string().name("onboarding_status"),
  createdAt: __t.timestamp().name("created_at"),
});
