// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  actionId: __t.string().primaryKey().name("action_id"),
  kind: __t.string(),
  groupId: __t.option(__t.string()).name("group_id"),
  toPhone: __t.option(__t.string()).name("to_phone"),
  targetMessageId: __t.option(__t.string()).name("target_message_id"),
  text: __t.option(__t.string()),
  reaction: __t.option(__t.string()),
  expenseId: __t.option(__t.string()).name("expense_id"),
  purpose: __t.string(),
  sendAfter: __t.timestamp().name("send_after"),
  status: __t.string(),
});
