// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  ledgerMemberId: __t.string().primaryKey().name("ledger_member_id"),
  ledgerGroupId: __t.string().name("ledger_group_id"),
  name: __t.option(__t.string()),
  bankBalanceCents: __t.option(__t.i64()).name("bank_balance_cents"),
});
